---
- name: Установка Docker, Node Exporter и Nginx в контейнерах
  hosts: your_debian_host
  become: yes
  tasks:
    - name: Обновить кеш пакетов
      apt:
        update_cache: yes

    - name: Установить зависимости
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Установить Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
        state: present
      notify: 
        - Update apt and install docker-ce

    - name: Update apt and install docker-ce
      apt:
        update_cache: yes
        name: docker-ce
        state: present

    - name: Запустить сервис Docker и настроить автозапуск
      service:
        name: docker
        enabled: yes
        state: started

    - name: Установить Node Exporter в Docker-контейнере
      docker_container:
        name: node_exporter
        image: prom/node-exporter
        ports:
          - "9100:9100"
        restart_policy: always

    - name: Установить Nginx в Docker-контейнере
      docker_container:
        name: nginx
        image: nginx
        ports:
          - "80:80"
        restart_policy: always