---
- name: Установка Docker, Node Exporter и Nginx в контейнерах на Alma Linux
  hosts: all
  become: yes
  
  tasks:
    - block: #===AlmaLinux===#
        - name: Обновить кеш пакетов
          dnf:
            update_cache: yes
          become: yes

        - name: Установить зависимости
          dnf:
            name:
              - dnf-plugins-core
              - curl
              - yum-utils
            state: present
          become: yes

        - name: Добавить репозиторий Docker
          shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          become: yes

        - name: Установить зависимости
          dnf:
            name:
              - containerd.io
              - docker-ce   
              - docker-ce-cli
              - docker-compose-plugin
            state: present
            allowerasing: yes
          become: yes

        - name: Запустить сервис Docker и настроить автозапуск
          service:
            name: docker
            enabled: yes
            state: started

        - name: Скачать Node Exporter
          get_url:
            url: "https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz"
            dest: "/tmp/node_exporter.tar.gz"
          become: yes

        - name: Распаковать Node Exporter
          ansible.builtin.unarchive:
            src: "/tmp/node_exporter.tar.gz"
            dest: "/opt/"
            remote_src: yes
          become: yes

        - name: Переименовать папку Node Exporter
          shell: mv /opt/node_exporter-* /opt/node_exporter
          become: yes

        - name: Создать systemd unit для Node Exporter
          template:
            src: node_exporter.service.j2
            dest: /etc/systemd/system/node_exporter.service
          become: yes

        - name: Запустить Node Exporter и настроить автозапуск
          service:
            name: node_exporter
            enabled: yes
            state: started
          become: yes

        - name: Создать директорию для пользовательских конфигов Nginx
          file:
            path: /nginx/config
            state: directory
          become: yes

        - name: Копировать пользовательский файл конфигурации Nginx в контейнер
          copy:
            src: nginx.conf
            dest: /nginx/config/nginx.conf
          become: yes

        - name: Установить Nginx в Docker-контейнере
          docker_container:
            name: nginx
            image: nginx
            ports:
              - "80:80"
            volumes:
              - /nginx/config/:/etc/nginx/conf.d/:ro
            restart_policy: always
          become: yes

      when: ansible_pkg_mgr == "dnf"    

    - block:  #===Debian\Ubuntu===#
        - name: Обновить кеш пакетов
          apt:
            update_cache: yes

        - name: Установить зависимости
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - software-properties-common
              - gnupg
            state: present

        - name: Добавить репозиторий Docker
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
            state: present

        - name: Добавить репозиторий Docker
          shell: sudo install -m 0755 -d /etc/apt/keyrings & curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg & sudo chmod a+r /etc/apt/keyrings/docker.gpg
          become: yes

        - name: Update apt and install docker-ce
          apt:
            update_cache: yes
            name: docker-ce
            state: present

        - name: Запустить сервис Docker и настроить автозапуск
          service:
            name: docker
            enabled: yes
            state: started

        - name: Скачать Node Exporter
          get_url:
            url: "https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz"
            dest: "/tmp/node_exporter.tar.gz"

        - name: Распаковать Node Exporter
          ansible.builtin.unarchive:
            src: "/tmp/node_exporter.tar.gz"
            dest: "/opt/"
            remote_src: yes
          become: yes

        - name: Переименовать папку Node Exporter
          shell: mv /opt/node_exporter-* /opt/node_exporter
          become: yes

        - name: Создать systemd unit для Node Exporter
          template:
            src: node_exporter.service.j2
            dest: /etc/systemd/system/node_exporter.service

        - name: Запустить Node Exporter и настроить автозапуск
          service:
            name: node_exporter
            enabled: yes
            state: started

        - name: Создать директорию для пользовательских конфигов Nginx
          file:
            path: /nginx/config
            state: directory

        - name: Копировать пользовательский файл конфигурации Nginx в контейнер
          copy:
            src: nginx.conf
            dest: /nginx/config/nginx.conf

        - name: Установить Nginx в Docker-контейнере
          docker_container:
            name: nginx
            image: nginx
            ports:
              - "80:80"
            volumes:
              - /nginx/config/:/etc/nginx/conf.d/:ro
            restart_policy: always
    
      when: ansible_pkg_mgr == "apt"   